services:
  - type: web
    name: intern-backend
    env: node
    region: oregon
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    autoDeploy: true
    disk:
      name: sqlite-data
      mountPath: /opt/render/project/src/data
      sizeGB: 1
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: JWT_SECRET
        sync: false
      - key: DB_PATH
        value: /opt/render/project/src/data/database.sqlite
    headers:
      - path: /*
        name: Access-Control-Allow-Origin
        value: "*"